apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: replicas-patch.yaml

images:
  - name: registry.gitlab.com/tutum-project/tutum-app/backend/frontend
    newTag: d0c71f0f
  - name: registry.gitlab.com/tutum-project/tutum-app/backend
    newTag: d0c71f0f
  - name: registry.gitlab.com/tutum-project/tutum-app/backend/workers
    newTag: d0c71f0f
